### ISSUE TITLE
Yellow line appears when I scrooll up in navigation bar

### ISSUE THREAD

**Issue by GarvTambi** [GarvTambi/JaipurMasale#3]
![Uploading Screenshot 2024-07-26 at 10.08.19 AM.png…]()

**Comment by nishant23122000** [comment]
Can't see the png file @GarvTambi

**Comment by GarvTambi** [comment]
<img width="1438" alt="Screenshot 2024-07-26 at 10 08 19 AM" src="https://github.com/user-attachments/assets/acde9202-afe2-4b07-aa41-840d82da8ecb">
