### ISSUE TITLE
Revies are not scrolling automatically or not having any animation

### ISSUE THREAD

**Issue by GarvTambi** [GarvTambi/JaipurMasale#4]
![Uploading Screenshot 2024-07-26 at 10.15.16 AM.png…]()

**Comment by nishant23122000** [comment]
Can't see it

**Comment by GarvTambi** [comment]
kya see nhi kr paa rhe ??

**Comment by GarvTambi** [comment]
<img width="1426" alt="Screenshot 2024-07-26 at 10 15 16 AM" src="https://github.com/user-attachments/assets/e727908a-1afc-469b-a453-e31f6c10455f">
